package com.blockchain.componentlib.icons

import com.blockchain.componentlib.basic.ImageResource

val Icons.Filled.Academy: ImageResource.Local
    get() = ImageResource.Local(R.drawable.academy_on)
val Icons.Filled.Activity: ImageResource.Local
    get() = ImageResource.Local(R.drawable.activity_on)
val Icons.Filled.Airdrop: ImageResource.Local
    get() = ImageResource.Local(R.drawable.airdrop_on)
val Icons.Filled.Alert: ImageResource.Local
    get() = ImageResource.Local(R.drawable.alert_on)
val Icons.Filled.Android: ImageResource.Local
    get() = ImageResource.Local(R.drawable.android_on)
val Icons.Filled.Apple: ImageResource.Local
    get() = ImageResource.Local(R.drawable.apple_on)
val Icons.Filled.ArrowDown: ImageResource.Local
    get() = ImageResource.Local(R.drawable.arrow_down_on)
val Icons.Filled.ArrowLeft: ImageResource.Local
    get() = ImageResource.Local(R.drawable.arrow_left_on)
val Icons.Filled.ArrowRight: ImageResource.Local
    get() = ImageResource.Local(R.drawable.arrow_right_on)
val Icons.Filled.ArrowUp: ImageResource.Local
    get() = ImageResource.Local(R.drawable.arrow_up_on)
val Icons.Filled.Backspace: ImageResource.Local
    get() = ImageResource.Local(R.drawable.backspace_on)
val Icons.Filled.Backup: ImageResource.Local
    get() = ImageResource.Local(R.drawable.backup_on)
val Icons.Filled.Bank: ImageResource.Local
    get() = ImageResource.Local(R.drawable.bank_on)
val Icons.Filled.BellOff: ImageResource.Local
    get() = ImageResource.Local(R.drawable.bell_off_on)
val Icons.Filled.Bell: ImageResource.Local
    get() = ImageResource.Local(R.drawable.bell_on)
val Icons.Filled.Blockchain: ImageResource.Local
    get() = ImageResource.Local(R.drawable.blockchain_on)
val Icons.Filled.Calendar: ImageResource.Local
    get() = ImageResource.Local(R.drawable.calendar_on)
val Icons.Filled.Call: ImageResource.Local
    get() = ImageResource.Local(R.drawable.call_on)
val Icons.Filled.Camera: ImageResource.Local
    get() = ImageResource.Local(R.drawable.camera_on)
val Icons.Filled.Card: ImageResource.Local
    get() = ImageResource.Local(R.drawable.card_on)
val Icons.Filled.Cart: ImageResource.Local
    get() = ImageResource.Local(R.drawable.cart_on)
val Icons.Filled.Cash: ImageResource.Local
    get() = ImageResource.Local(R.drawable.cash_on)
val Icons.Filled.Chart: ImageResource.Local
    get() = ImageResource.Local(R.drawable.chart_on)
val Icons.Filled.ChartsBubble: ImageResource.Local
    get() = ImageResource.Local(R.drawable.charts_bubble_on)
val Icons.Filled.ChartsLine: ImageResource.Local
    get() = ImageResource.Local(R.drawable.charts_line_on)
val Icons.Filled.Chat: ImageResource.Local
    get() = ImageResource.Local(R.drawable.chat_on)
val Icons.Filled.Check: ImageResource.Local
    get() = ImageResource.Local(R.drawable.check_on)
val Icons.Filled.ChevronDown: ImageResource.Local
    get() = ImageResource.Local(R.drawable.chevron_down_on)
val Icons.Filled.ChevronLeft: ImageResource.Local
    get() = ImageResource.Local(R.drawable.chevron_left_on)
val Icons.Filled.ChevronRight: ImageResource.Local
    get() = ImageResource.Local(R.drawable.chevron_right_on)
val Icons.Filled.ChevronUp: ImageResource.Local
    get() = ImageResource.Local(R.drawable.chevron_up_on)
val Icons.Filled.Clipboard: ImageResource.Local
    get() = ImageResource.Local(R.drawable.clipboard_on)
val Icons.Filled.Close: ImageResource.Local
    get() = ImageResource.Local(R.drawable.close_on)
val Icons.Filled.CloudCheck: ImageResource.Local
    get() = ImageResource.Local(R.drawable.cloud_check_on)
val Icons.Filled.CloudDownload: ImageResource.Local
    get() = ImageResource.Local(R.drawable.cloud_download_on)
val Icons.Filled.Cloud: ImageResource.Local
    get() = ImageResource.Local(R.drawable.cloud_on)
val Icons.Filled.CloudUpload: ImageResource.Local
    get() = ImageResource.Local(R.drawable.cloud_upload_on)
val Icons.Filled.Code: ImageResource.Local
    get() = ImageResource.Local(R.drawable.code_on)
val Icons.Filled.Coins: ImageResource.Local
    get() = ImageResource.Local(R.drawable.coins_on)
val Icons.Filled.ColorPicker: ImageResource.Local
    get() = ImageResource.Local(R.drawable.color_picker_on)
val Icons.Filled.Components: ImageResource.Local
    get() = ImageResource.Local(R.drawable.components_on)
val Icons.Filled.Copy: ImageResource.Local
    get() = ImageResource.Local(R.drawable.copy_on)
val Icons.Filled.Defi: ImageResource.Local
    get() = ImageResource.Local(R.drawable.defi_on)
val Icons.Filled.Delete: ImageResource.Local
    get() = ImageResource.Local(R.drawable.delete_on)
val Icons.Filled.Developer: ImageResource.Local
    get() = ImageResource.Local(R.drawable.developer_on)
val Icons.Filled.Edit: ImageResource.Local
    get() = ImageResource.Local(R.drawable.edit_on)
val Icons.Filled.Email: ImageResource.Local
    get() = ImageResource.Local(R.drawable.email_on)
val Icons.Filled.Emoji: ImageResource.Local
    get() = ImageResource.Local(R.drawable.emoji_on)
val Icons.Filled.Equals: ImageResource.Local
    get() = ImageResource.Local(R.drawable.equals_on)
val Icons.Filled.Error: ImageResource.Local
    get() = ImageResource.Local(R.drawable.error_on)
val Icons.Filled.Explore: ImageResource.Local
    get() = ImageResource.Local(R.drawable.explore_on)
val Icons.Filled.Faceid: ImageResource.Local
    get() = ImageResource.Local(R.drawable.faceid_on)
val Icons.Filled.Filter: ImageResource.Local
    get() = ImageResource.Local(R.drawable.filter_on)
val Icons.Filled.Fingerprint: ImageResource.Local
    get() = ImageResource.Local(R.drawable.fingerprint_on)
val Icons.Filled.Flag: ImageResource.Local
    get() = ImageResource.Local(R.drawable.flag_on)
val Icons.Filled.FlashOff: ImageResource.Local
    get() = ImageResource.Local(R.drawable.flash_off_on)
val Icons.Filled.FlashOn: ImageResource.Local
    get() = ImageResource.Local(R.drawable.flash_on_on)
val Icons.Filled.Flip: ImageResource.Local
    get() = ImageResource.Local(R.drawable.flip_on)
val Icons.Filled.Folder: ImageResource.Local
    get() = ImageResource.Local(R.drawable.folder_on)
val Icons.Filled.Formula: ImageResource.Local
    get() = ImageResource.Local(R.drawable.formula_on)
val Icons.Filled.FullscreenExit: ImageResource.Local
    get() = ImageResource.Local(R.drawable.fullscreen_exit_on)
val Icons.Filled.Fullscreen: ImageResource.Local
    get() = ImageResource.Local(R.drawable.fullscreen_on)
val Icons.Filled.Gaming: ImageResource.Local
    get() = ImageResource.Local(R.drawable.gaming_on)
val Icons.Filled.Gas: ImageResource.Local
    get() = ImageResource.Local(R.drawable.gas_on)
val Icons.Filled.Gift: ImageResource.Local
    get() = ImageResource.Local(R.drawable.gift_on)
val Icons.Filled.Globe: ImageResource.Local
    get() = ImageResource.Local(R.drawable.globe_on)
val Icons.Filled.Grid: ImageResource.Local
    get() = ImageResource.Local(R.drawable.grid_on)
val Icons.Filled.Hardware: ImageResource.Local
    get() = ImageResource.Local(R.drawable.hardware_on)
val Icons.Filled.Home: ImageResource.Local
    get() = ImageResource.Local(R.drawable.home_on)
val Icons.Filled.Identification: ImageResource.Local
    get() = ImageResource.Local(R.drawable.identification_on)
val Icons.Filled.Image: ImageResource.Local
    get() = ImageResource.Local(R.drawable.image_on)
val Icons.Filled.Indicators: ImageResource.Local
    get() = ImageResource.Local(R.drawable.indicators_on)
val Icons.Filled.Info: ImageResource.Local
    get() = ImageResource.Local(R.drawable.info_on)
val Icons.Filled.Interest: ImageResource.Local
    get() = ImageResource.Local(R.drawable.interest_on)
val Icons.Filled.Key: ImageResource.Local
    get() = ImageResource.Local(R.drawable.key_on)
val Icons.Filled.Keyboard: ImageResource.Local
    get() = ImageResource.Local(R.drawable.keyboard_on)
val Icons.Filled.Language: ImageResource.Local
    get() = ImageResource.Local(R.drawable.language_on)
val Icons.Filled.Laptop: ImageResource.Local
    get() = ImageResource.Local(R.drawable.laptop_on)
val Icons.Filled.Legal: ImageResource.Local
    get() = ImageResource.Local(R.drawable.legal_on)
val Icons.Filled.Link: ImageResource.Local
    get() = ImageResource.Local(R.drawable.link_on)
val Icons.Filled.Lock: ImageResource.Local
    get() = ImageResource.Local(R.drawable.lock_on)
val Icons.Filled.Logout: ImageResource.Local
    get() = ImageResource.Local(R.drawable.logout_on)
val Icons.Filled.Math: ImageResource.Local
    get() = ImageResource.Local(R.drawable.math_on)
val Icons.Filled.MenuKebabHorizontal: ImageResource.Local
    get() = ImageResource.Local(R.drawable.menu_kebab_horizontal_on)
val Icons.Filled.MenuKebabVertical: ImageResource.Local
    get() = ImageResource.Local(R.drawable.menu_kebab_vertical_on)
val Icons.Filled.Menu: ImageResource.Local
    get() = ImageResource.Local(R.drawable.menu_on)
val Icons.Filled.MicrophoneOff: ImageResource.Local
    get() = ImageResource.Local(R.drawable.microphone_off_on)
val Icons.Filled.Microphone: ImageResource.Local
    get() = ImageResource.Local(R.drawable.microphone_on)
val Icons.Filled.Minus: ImageResource.Local
    get() = ImageResource.Local(R.drawable.minus_on)
val Icons.Filled.Mobile: ImageResource.Local
    get() = ImageResource.Local(R.drawable.mobile_on)
val Icons.Filled.Moon: ImageResource.Local
    get() = ImageResource.Local(R.drawable.moon_on)
val Icons.Filled.Move: ImageResource.Local
    get() = ImageResource.Local(R.drawable.move_on)
val Icons.Filled.Network: ImageResource.Local
    get() = ImageResource.Local(R.drawable.network_on)
val Icons.Filled.NewWindow: ImageResource.Local
    get() = ImageResource.Local(R.drawable.new_window_on)
val Icons.Filled.News: ImageResource.Local
    get() = ImageResource.Local(R.drawable.news_on)
val Icons.Filled.Nft: ImageResource.Local
    get() = ImageResource.Local(R.drawable.nft_on)
val Icons.Filled.Pay: ImageResource.Local
    get() = ImageResource.Local(R.drawable.pay_on)
val Icons.Filled.Pending: ImageResource.Local
    get() = ImageResource.Local(R.drawable.pending_on)
val Icons.Filled.Pin: ImageResource.Local
    get() = ImageResource.Local(R.drawable.pin_on)
val Icons.Filled.Placeholder: ImageResource.Local
    get() = ImageResource.Local(R.drawable.placeholder_on)
val Icons.Filled.Play: ImageResource.Local
    get() = ImageResource.Local(R.drawable.play_on)
val Icons.Filled.Plus: ImageResource.Local
    get() = ImageResource.Local(R.drawable.plus_on)
val Icons.Filled.Portfolio: ImageResource.Local
    get() = ImageResource.Local(R.drawable.portfolio_on)
val Icons.Filled.Prices: ImageResource.Local
    get() = ImageResource.Local(R.drawable.prices_on)
val Icons.Filled.Print: ImageResource.Local
    get() = ImageResource.Local(R.drawable.print_on)
val Icons.Filled.QrCode: ImageResource.Local
    get() = ImageResource.Local(R.drawable.qr_code_on)
val Icons.Filled.Question: ImageResource.Local
    get() = ImageResource.Local(R.drawable.question_on)
val Icons.Filled.Receive: ImageResource.Local
    get() = ImageResource.Local(R.drawable.receive_on)
val Icons.Filled.Refresh: ImageResource.Local
    get() = ImageResource.Local(R.drawable.refresh_on)
val Icons.Filled.Rewards: ImageResource.Local
    get() = ImageResource.Local(R.drawable.rewards_on)
val Icons.Filled.Satoshi: ImageResource.Local
    get() = ImageResource.Local(R.drawable.satoshi_on)
val Icons.Filled.Search: ImageResource.Local
    get() = ImageResource.Local(R.drawable.search_on)
val Icons.Filled.Security: ImageResource.Local
    get() = ImageResource.Local(R.drawable.security_on)
val Icons.Filled.Send: ImageResource.Local
    get() = ImageResource.Local(R.drawable.send_on)
val Icons.Filled.Settings: ImageResource.Local
    get() = ImageResource.Local(R.drawable.settings_on)
val Icons.Filled.Share: ImageResource.Local
    get() = ImageResource.Local(R.drawable.share_on)
val Icons.Filled.Signature: ImageResource.Local
    get() = ImageResource.Local(R.drawable.signature_on)
val Icons.Filled.Star: ImageResource.Local
    get() = ImageResource.Local(R.drawable.star_on)
val Icons.Filled.Subdirectory: ImageResource.Local
    get() = ImageResource.Local(R.drawable.subdirectory_on)
val Icons.Filled.Sun: ImageResource.Local
    get() = ImageResource.Local(R.drawable.sun_on)
val Icons.Filled.Swap: ImageResource.Local
    get() = ImageResource.Local(R.drawable.swap_on)
val Icons.Filled.Sync: ImageResource.Local
    get() = ImageResource.Local(R.drawable.sync_on)
val Icons.Filled.Timeout: ImageResource.Local
    get() = ImageResource.Local(R.drawable.timeout_on)
val Icons.Filled.TorBrowser: ImageResource.Local
    get() = ImageResource.Local(R.drawable.tor_browser_on)
val Icons.Filled.TrendLine: ImageResource.Local
    get() = ImageResource.Local(R.drawable.trend_line_on)
val Icons.Filled.TriangleDown: ImageResource.Local
    get() = ImageResource.Local(R.drawable.triangle_down_on)
val Icons.Filled.TriangleUp: ImageResource.Local
    get() = ImageResource.Local(R.drawable.triangle_up_on)
val Icons.Filled.UnfoldLess: ImageResource.Local
    get() = ImageResource.Local(R.drawable.unfold_less_on)
val Icons.Filled.UnfoldMore: ImageResource.Local
    get() = ImageResource.Local(R.drawable.unfold_more_on)
val Icons.Filled.Unlink: ImageResource.Local
    get() = ImageResource.Local(R.drawable.unlink_on)
val Icons.Filled.Unlock: ImageResource.Local
    get() = ImageResource.Local(R.drawable.unlock_on)
val Icons.Filled.Usd: ImageResource.Local
    get() = ImageResource.Local(R.drawable.usd_on)
val Icons.Filled.UserAdd: ImageResource.Local
    get() = ImageResource.Local(R.drawable.user_add_on)
val Icons.Filled.User: ImageResource.Local
    get() = ImageResource.Local(R.drawable.user_on)
val Icons.Filled.Users: ImageResource.Local
    get() = ImageResource.Local(R.drawable.users_on)
val Icons.Filled.Verified: ImageResource.Local
    get() = ImageResource.Local(R.drawable.verified_on)
val Icons.Filled.Viewfinder: ImageResource.Local
    get() = ImageResource.Local(R.drawable.viewfinder_on)
val Icons.Filled.VisibleOff: ImageResource.Local
    get() = ImageResource.Local(R.drawable.visible_off_on)
val Icons.Filled.Visible: ImageResource.Local
    get() = ImageResource.Local(R.drawable.visible_on)
val Icons.Filled.Wallet: ImageResource.Local
    get() = ImageResource.Local(R.drawable.wallet_on)
