package com.blockchain.componentlib.icons

import com.blockchain.componentlib.basic.ImageResource

val Icons.Academy: ImageResource.Local
    get() = ImageResource.Local(R.drawable.academy_off)
val Icons.Activity: ImageResource.Local
    get() = ImageResource.Local(R.drawable.activity_off)
val Icons.Airdrop: ImageResource.Local
    get() = ImageResource.Local(R.drawable.airdrop_off)
val Icons.Alert: ImageResource.Local
    get() = ImageResource.Local(R.drawable.alert_off)
val Icons.Android: ImageResource.Local
    get() = ImageResource.Local(R.drawable.android_off)
val Icons.Apple: ImageResource.Local
    get() = ImageResource.Local(R.drawable.apple_off)
val Icons.ArrowDown: ImageResource.Local
    get() = ImageResource.Local(R.drawable.arrow_down_off)
val Icons.ArrowLeft: ImageResource.Local
    get() = ImageResource.Local(R.drawable.arrow_left_off)
val Icons.ArrowRight: ImageResource.Local
    get() = ImageResource.Local(R.drawable.arrow_right_off)
val Icons.ArrowUp: ImageResource.Local
    get() = ImageResource.Local(R.drawable.arrow_up_off)
val Icons.Backspace: ImageResource.Local
    get() = ImageResource.Local(R.drawable.backspace_off)
val Icons.Backup: ImageResource.Local
    get() = ImageResource.Local(R.drawable.backup_off)
val Icons.Bank: ImageResource.Local
    get() = ImageResource.Local(R.drawable.bank_off)
val Icons.Bell: ImageResource.Local
    get() = ImageResource.Local(R.drawable.bell_off)
val Icons.BellOff: ImageResource.Local
    get() = ImageResource.Local(R.drawable.bell_off_off)
val Icons.Blockchain: ImageResource.Local
    get() = ImageResource.Local(R.drawable.blockchain_off)
val Icons.Calendar: ImageResource.Local
    get() = ImageResource.Local(R.drawable.calendar_off)
val Icons.Call: ImageResource.Local
    get() = ImageResource.Local(R.drawable.call_off)
val Icons.Camera: ImageResource.Local
    get() = ImageResource.Local(R.drawable.camera_off)
val Icons.Card: ImageResource.Local
    get() = ImageResource.Local(R.drawable.card_off)
val Icons.Cart: ImageResource.Local
    get() = ImageResource.Local(R.drawable.cart_off)
val Icons.Cash: ImageResource.Local
    get() = ImageResource.Local(R.drawable.cash_off)
val Icons.Chart: ImageResource.Local
    get() = ImageResource.Local(R.drawable.chart_off)
val Icons.ChartsBubble: ImageResource.Local
    get() = ImageResource.Local(R.drawable.charts_bubble_off)
val Icons.ChartsLine: ImageResource.Local
    get() = ImageResource.Local(R.drawable.charts_line_off)
val Icons.Chat: ImageResource.Local
    get() = ImageResource.Local(R.drawable.chat_off)
val Icons.Check: ImageResource.Local
    get() = ImageResource.Local(R.drawable.check_off)
val Icons.ChevronDown: ImageResource.Local
    get() = ImageResource.Local(R.drawable.chevron_down_off)
val Icons.ChevronLeft: ImageResource.Local
    get() = ImageResource.Local(R.drawable.chevron_left_off)
val Icons.ChevronRight: ImageResource.Local
    get() = ImageResource.Local(R.drawable.chevron_right_off)
val Icons.ChevronUp: ImageResource.Local
    get() = ImageResource.Local(R.drawable.chevron_up_off)
val Icons.Clipboard: ImageResource.Local
    get() = ImageResource.Local(R.drawable.clipboard_off)
val Icons.Close: ImageResource.Local
    get() = ImageResource.Local(R.drawable.close_off)
val Icons.CloudCheck: ImageResource.Local
    get() = ImageResource.Local(R.drawable.cloud_check_off)
val Icons.CloudDownload: ImageResource.Local
    get() = ImageResource.Local(R.drawable.cloud_download_off)
val Icons.Cloud: ImageResource.Local
    get() = ImageResource.Local(R.drawable.cloud_off)
val Icons.CloudUpload: ImageResource.Local
    get() = ImageResource.Local(R.drawable.cloud_upload_off)
val Icons.Code: ImageResource.Local
    get() = ImageResource.Local(R.drawable.code_off)
val Icons.Coins: ImageResource.Local
    get() = ImageResource.Local(R.drawable.coins_off)
val Icons.ColorPicker: ImageResource.Local
    get() = ImageResource.Local(R.drawable.color_picker_off)
val Icons.Components: ImageResource.Local
    get() = ImageResource.Local(R.drawable.components_off)
val Icons.Copy: ImageResource.Local
    get() = ImageResource.Local(R.drawable.copy_off)
val Icons.Defi: ImageResource.Local
    get() = ImageResource.Local(R.drawable.defi_off)
val Icons.Delete: ImageResource.Local
    get() = ImageResource.Local(R.drawable.delete_off)
val Icons.Developer: ImageResource.Local
    get() = ImageResource.Local(R.drawable.developer_off)
val Icons.Edit: ImageResource.Local
    get() = ImageResource.Local(R.drawable.edit_off)
val Icons.Email: ImageResource.Local
    get() = ImageResource.Local(R.drawable.email_off)
val Icons.Emoji: ImageResource.Local
    get() = ImageResource.Local(R.drawable.emoji_off)
val Icons.Equals: ImageResource.Local
    get() = ImageResource.Local(R.drawable.equals_off)
val Icons.Error: ImageResource.Local
    get() = ImageResource.Local(R.drawable.error_off)
val Icons.Explore: ImageResource.Local
    get() = ImageResource.Local(R.drawable.explore_off)
val Icons.Faceid: ImageResource.Local
    get() = ImageResource.Local(R.drawable.faceid_off)
val Icons.Filter: ImageResource.Local
    get() = ImageResource.Local(R.drawable.filter_off)
val Icons.Fingerprint: ImageResource.Local
    get() = ImageResource.Local(R.drawable.fingerprint_off)
val Icons.Flag: ImageResource.Local
    get() = ImageResource.Local(R.drawable.flag_off)
val Icons.FlashOff: ImageResource.Local
    get() = ImageResource.Local(R.drawable.flash_off_off)
val Icons.FlashOn: ImageResource.Local
    get() = ImageResource.Local(R.drawable.flash_on_off)
val Icons.Flip: ImageResource.Local
    get() = ImageResource.Local(R.drawable.flip_off)
val Icons.Folder: ImageResource.Local
    get() = ImageResource.Local(R.drawable.folder_off)
val Icons.Formula: ImageResource.Local
    get() = ImageResource.Local(R.drawable.formula_off)
val Icons.FullscreenExit: ImageResource.Local
    get() = ImageResource.Local(R.drawable.fullscreen_exit_off)
val Icons.Fullscreen: ImageResource.Local
    get() = ImageResource.Local(R.drawable.fullscreen_off)
val Icons.Gaming: ImageResource.Local
    get() = ImageResource.Local(R.drawable.gaming_off)
val Icons.Gas: ImageResource.Local
    get() = ImageResource.Local(R.drawable.gas_off)
val Icons.Gift: ImageResource.Local
    get() = ImageResource.Local(R.drawable.gift_off)
val Icons.Globe: ImageResource.Local
    get() = ImageResource.Local(R.drawable.globe_off)
val Icons.Grid: ImageResource.Local
    get() = ImageResource.Local(R.drawable.grid_off)
val Icons.Hardware: ImageResource.Local
    get() = ImageResource.Local(R.drawable.hardware_off)
val Icons.Home: ImageResource.Local
    get() = ImageResource.Local(R.drawable.home_off)
val Icons.Identification: ImageResource.Local
    get() = ImageResource.Local(R.drawable.identification_off)
val Icons.Image: ImageResource.Local
    get() = ImageResource.Local(R.drawable.image_off)
val Icons.Indicators: ImageResource.Local
    get() = ImageResource.Local(R.drawable.indicators_off)
val Icons.Info: ImageResource.Local
    get() = ImageResource.Local(R.drawable.info_off)
val Icons.Interest: ImageResource.Local
    get() = ImageResource.Local(R.drawable.interest_off)
val Icons.Key: ImageResource.Local
    get() = ImageResource.Local(R.drawable.key_off)
val Icons.Keyboard: ImageResource.Local
    get() = ImageResource.Local(R.drawable.keyboard_off)
val Icons.Language: ImageResource.Local
    get() = ImageResource.Local(R.drawable.language_off)
val Icons.Laptop: ImageResource.Local
    get() = ImageResource.Local(R.drawable.laptop_off)
val Icons.Legal: ImageResource.Local
    get() = ImageResource.Local(R.drawable.legal_off)
val Icons.Link: ImageResource.Local
    get() = ImageResource.Local(R.drawable.link_off)
val Icons.Lock: ImageResource.Local
    get() = ImageResource.Local(R.drawable.lock_off)
val Icons.Logout: ImageResource.Local
    get() = ImageResource.Local(R.drawable.logout_off)
val Icons.Math: ImageResource.Local
    get() = ImageResource.Local(R.drawable.math_off)
val Icons.MenuKebabHorizontal: ImageResource.Local
    get() = ImageResource.Local(R.drawable.menu_kebab_horizontal_off)
val Icons.MenuKebabVertical: ImageResource.Local
    get() = ImageResource.Local(R.drawable.menu_kebab_vertical_off)
val Icons.Menu: ImageResource.Local
    get() = ImageResource.Local(R.drawable.menu_off)
val Icons.Microphone: ImageResource.Local
    get() = ImageResource.Local(R.drawable.microphone_off)
val Icons.MicrophoneOff: ImageResource.Local
    get() = ImageResource.Local(R.drawable.microphone_off_off)
val Icons.Minus: ImageResource.Local
    get() = ImageResource.Local(R.drawable.minus_off)
val Icons.Mobile: ImageResource.Local
    get() = ImageResource.Local(R.drawable.mobile_off)
val Icons.Moon: ImageResource.Local
    get() = ImageResource.Local(R.drawable.moon_off)
val Icons.Move: ImageResource.Local
    get() = ImageResource.Local(R.drawable.move_off)
val Icons.Network: ImageResource.Local
    get() = ImageResource.Local(R.drawable.network_off)
val Icons.NewWindow: ImageResource.Local
    get() = ImageResource.Local(R.drawable.new_window_off)
val Icons.News: ImageResource.Local
    get() = ImageResource.Local(R.drawable.news_off)
val Icons.Nft: ImageResource.Local
    get() = ImageResource.Local(R.drawable.nft_off)
val Icons.Pay: ImageResource.Local
    get() = ImageResource.Local(R.drawable.pay_off)
val Icons.Pending: ImageResource.Local
    get() = ImageResource.Local(R.drawable.pending_off)
val Icons.Pin: ImageResource.Local
    get() = ImageResource.Local(R.drawable.pin_off)
val Icons.Placeholder: ImageResource.Local
    get() = ImageResource.Local(R.drawable.placeholder_off)
val Icons.Play: ImageResource.Local
    get() = ImageResource.Local(R.drawable.play_off)
val Icons.Plus: ImageResource.Local
    get() = ImageResource.Local(R.drawable.plus_off)
val Icons.Portfolio: ImageResource.Local
    get() = ImageResource.Local(R.drawable.portfolio_off)
val Icons.Prices: ImageResource.Local
    get() = ImageResource.Local(R.drawable.prices_off)
val Icons.Print: ImageResource.Local
    get() = ImageResource.Local(R.drawable.print_off)
val Icons.QrCode: ImageResource.Local
    get() = ImageResource.Local(R.drawable.qr_code_off)
val Icons.Question: ImageResource.Local
    get() = ImageResource.Local(R.drawable.question_off)
val Icons.Receive: ImageResource.Local
    get() = ImageResource.Local(R.drawable.receive_off)
val Icons.Refresh: ImageResource.Local
    get() = ImageResource.Local(R.drawable.refresh_off)
val Icons.Rewards: ImageResource.Local
    get() = ImageResource.Local(R.drawable.rewards_off)
val Icons.Rocket: ImageResource.Local
    get() = ImageResource.Local(R.drawable.rocket_off)
val Icons.Satoshi: ImageResource.Local
    get() = ImageResource.Local(R.drawable.satoshi_off)
val Icons.Search: ImageResource.Local
    get() = ImageResource.Local(R.drawable.search_off)
val Icons.Security: ImageResource.Local
    get() = ImageResource.Local(R.drawable.security_off)
val Icons.Send: ImageResource.Local
    get() = ImageResource.Local(R.drawable.send_off)
val Icons.Settings: ImageResource.Local
    get() = ImageResource.Local(R.drawable.settings_off)
val Icons.Share: ImageResource.Local
    get() = ImageResource.Local(R.drawable.share_off)
val Icons.Signature: ImageResource.Local
    get() = ImageResource.Local(R.drawable.signature_off)
val Icons.Star: ImageResource.Local
    get() = ImageResource.Local(R.drawable.star_off)
val Icons.Subdirectory: ImageResource.Local
    get() = ImageResource.Local(R.drawable.subdirectory_off)
val Icons.Sun: ImageResource.Local
    get() = ImageResource.Local(R.drawable.sun_off)
val Icons.Swap: ImageResource.Local
    get() = ImageResource.Local(R.drawable.swap_off)
val Icons.Sync: ImageResource.Local
    get() = ImageResource.Local(R.drawable.sync_off)
val Icons.Timeout: ImageResource.Local
    get() = ImageResource.Local(R.drawable.timeout_off)
val Icons.TorBrowser: ImageResource.Local
    get() = ImageResource.Local(R.drawable.tor_browser_off)
val Icons.TrendLine: ImageResource.Local
    get() = ImageResource.Local(R.drawable.trend_line_off)
val Icons.TriangleDown: ImageResource.Local
    get() = ImageResource.Local(R.drawable.triangle_down_off)
val Icons.TriangleUp: ImageResource.Local
    get() = ImageResource.Local(R.drawable.triangle_up_off)
val Icons.UnfoldLess: ImageResource.Local
    get() = ImageResource.Local(R.drawable.unfold_less_off)
val Icons.UnfoldMore: ImageResource.Local
    get() = ImageResource.Local(R.drawable.unfold_more_off)
val Icons.Unlink: ImageResource.Local
    get() = ImageResource.Local(R.drawable.unlink_off)
val Icons.Unlock: ImageResource.Local
    get() = ImageResource.Local(R.drawable.unlock_off)
val Icons.Usd: ImageResource.Local
    get() = ImageResource.Local(R.drawable.usd_off)
val Icons.UserAdd: ImageResource.Local
    get() = ImageResource.Local(R.drawable.user_add_off)
val Icons.User: ImageResource.Local
    get() = ImageResource.Local(R.drawable.user_off)
val Icons.Users: ImageResource.Local
    get() = ImageResource.Local(R.drawable.users_off)
val Icons.Verified: ImageResource.Local
    get() = ImageResource.Local(R.drawable.verified_off)
val Icons.Viewfinder: ImageResource.Local
    get() = ImageResource.Local(R.drawable.viewfinder_off)
val Icons.Visible: ImageResource.Local
    get() = ImageResource.Local(R.drawable.visible_off)
val Icons.VisibleOff: ImageResource.Local
    get() = ImageResource.Local(R.drawable.visible_off_off)
val Icons.Wallet: ImageResource.Local
    get() = ImageResource.Local(R.drawable.wallet_off)
